### ISSUE TITLE
npm run parse error

### ISSUE THREAD

**Issue by nickreich** [reichlab/flusight#22]
@lepisma Any ideas about the cause of this parsing error? 

```
flusight ngr$ node -v
v7.1.0
flusight ngr$ npm -v
3.10.9
flusight ngr$ npm run parse

> flusight@1.0.0 parse /Users/ngr/Documents/research-versioned/flusight
> node build/parse.js

Parsing files...

Found 2 seasons:
2015-2016
2016-2017

Gathering actual data for the seasons...
Parsing region: National
/Users/ngr/Documents/research-versioned/flusight/parse/modules/transform.js:185
  if (series[len - 1][0] == 'none') {
                     ^

TypeError: Cannot read property '0' of undefined
    at parseSeries (/Users/ngr/Documents/research-versioned/flusight/parse/modules/transform.js:185:22)
    at Object.longToJson (/Users/ngr/Documents/research-versioned/flusight/parse/modules/transform.js:276:20)
    at predictions.weeks.map.week (/Users/ngr/Documents/research-versioned/flusight/parse/parse.js:85:34)
    at Array.map (native)
    at modelsDir.map.model (/Users/ngr/Documents/research-versioned/flusight/parse/parse.js:76:32)
    at Array.map (native)
    at val.seasons.seasons.map.season (/Users/ngr/Documents/research-versioned/flusight/parse/parse.js:70:32)
    at Array.map (native)
    at output.forEach.val (/Users/ngr/Documents/research-versioned/flusight/parse/parse.js:67:29)
    at Array.forEach (native)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "run" "parse"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! flusight@1.0.0 parse: `node build/parse.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flusight@1.0.0 parse script 'node build/parse.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the flusight package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/parse.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs flusight
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls flusight
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ngr/Documents/research-versioned/flusight/npm-debug.log
```

**Comment by nickreich** [comment]
@lepisma I think the error is due to a minor change that I made in the format of one of the files. I'm checking into this now, don't think it is an error in the parser, although it might be nice for the parser to be insensitive to the ordering of rows...

**Comment by lepisma** [comment]
@nickreich if that works, specify the change you did in the file. Will make the parser work with it.

**Comment by lepisma** [comment]
1d04a90f0ce84785ba6feff8ca91ebfc19bdf2bd should accommodate this. The newer format, with parse error, doesn't have point predictions. I am using a better grouping method now, this should be robust for the change.
